// <auto-generated />
using J4JSoftware.Roslyn;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace J4JSoftware.Roslyn.Migrations
{
    [DbContext(typeof(RoslynDbContext))]
    [Migration("20200718171842_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("J4JSoftware.Roslyn.Assembly", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DotNetVersionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileVersionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FrameworkName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FrameworkVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullyQualifiedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageVersionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Synchronized")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasAlternateKey("FullyQualifiedName");

                    b.ToTable("Assemblies");
                });

            modelBuilder.Entity("J4JSoftware.Roslyn.InScopeAssemblyInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssemblyID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Copyright")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RootNamespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("InScopeInfo");
                });

            modelBuilder.Entity("J4JSoftware.Roslyn.Assembly", b =>
                {
                    b.HasOne("J4JSoftware.Roslyn.InScopeAssemblyInfo", "InScopeInfo")
                        .WithOne("Assembly")
                        .HasForeignKey("J4JSoftware.Roslyn.Assembly", "ID")
                        .HasPrincipalKey("J4JSoftware.Roslyn.InScopeAssemblyInfo", "AssemblyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
